--- # directory creation
- name: creation of test directory
  hosts: webservers
  user: ansible
  connection: ssh
  become: yes


  tasks: 
  - name: creation of folder
    file:
      path: /home/ansible/pradeep_dir
      state: directory
