--- # test handler session
- hosts: webservers
  user: ansible
  connection: ssh
  become: yes


  tasks:
    - name: installation of httpd
      action: yum name=httpd state=present
      notify: start httpd service


  handlers:
    - name: start httpd service
      action: service name=httpd state=started
