--- # creation for multiple users
- hosts: webservers
  become: true
    
  tasks:
    - name: creation of multiple users
      user: name='{{item}}' state=present
      with_items:
            - Raj
            - pavan
            - new
            - aaa
            - Mr
