---
- name: my loops playbook to install multiple SW
  hosts: webservers
  become: true


  tasks:
    - name: install packages
      yum:
        name: ['git','which','docker','mysql','tree','wget','httpd','java']
        state: installed

